In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tqdm import tqdm
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv('data/test_mod21c3.csv')
df.head()

year        date  [110.65896827426326, -3.0318140839033854]  \
0  2023  2023_01_01                                     307.18   
1  2023  2023_02_01                                     306.48   
2  2023  2023_03_01                                     306.02   
3  2023  2023_04_01                                     309.36   
4  2023  2023_05_01                                     307.72   

   [110.66795142710446, -3.0318140839033854]  \
0                                     307.18   
1                                     306.48   
2                                     306.02   
3                                     309.36   
4                                     307.72   

   [110.64998512142206, -3.02283093106219]  \
0                                   305.01   
1                                   304.50   
2                                   305.68   
3                                   307.48   
4                                   306.76   

   [110.65896827426326, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.66795142710446, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.67693457994565, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.68591773278685, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.64100196858087, -3.013847778220995]  ...  \
0                                    305.01  ...   
1                                    304.50  ...   
2                                    305.68  ...   
3                                    307.48  ...   
4                                    306.76  ...   

   [109.62590569752581, 2.016717812848326]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.61692254468461, 2.025700965689521]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.62590569752581, 2.025700965689521]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.61692254468461, 2.0346841185307163]  \
0                                    302.85   
1                                    300.26   
2                                    306.00   
3                                    305.48   
4                                    307.26   

   [109.62590569752581, 2.0346841185307163]  \
0                                    302.85   
1                                    300.26   
2                                    306.00   
3                                    305.48   
4                                    307.26   

   [109.62590569752581, 2.0436672713719113]  \
0                                    302.85   
1                                    300.26   
2                                    306.00   
3                                 

In [4]:
df = df.drop(columns=['year', 'date'])
df.head()

[110.65896827426326, -3.0318140839033854]  \
0                                     307.18   
1                                     306.48   
2                                     306.02   
3                                     309.36   
4                                     307.72   

   [110.66795142710446, -3.0318140839033854]  \
0                                     307.18   
1                                     306.48   
2                                     306.02   
3                                     309.36   
4                                     307.72   

   [110.64998512142206, -3.02283093106219]  \
0                                   305.01   
1                                   304.50   
2                                   305.68   
3                                   307.48   
4                                   306.76   

   [110.65896827426326, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.66795142710446, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.67693457994565, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.68591773278685, -3.02283093106219]  \
0                                   307.18   
1                                   306.48   
2                                   306.02   
3                                   309.36   
4                                   307.72   

   [110.64100196858087, -3.013847778220995]  \
0                                    305.01   
1                                    304.50   
2                                    305.68   
3                                    307.48   
4                                    306.76   

   [110.64998512142206, -3.013847778220995]  \
0                                    305.01   
1                                    304.50   
2                                    305.68   
3                                    307.48   
4                                    306.76   

   [110.65896827426326, -3.013847778220995]  ...  \
0                                    307.18  ...   
1                                    306.48  ...   
2                                    306.02  ...   
3                                    309.36  ...   
4                                    307.72  ...   

   [109.62590569752581, 2.016717812848326]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.61692254468461, 2.025700965689521]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.62590569752581, 2.025700965689521]  \
0                                   302.85   
1                                   300.26   
2                                   306.00   
3                                   305.48   
4                                   307.26   

   [109.61692254468461, 2.0346841185307163]  \
0                                    302.85   
1                                    300.26   
2                                    306.00   
3                                    305.48   
4                                    307.26   

   [109.62590569752581, 2.0346841185307163]  \


In [5]:
# Sliding Window
def create_window(dataframe, window_size, slide_size):
    input_window_list = []
    label_window_list = []
    # Iterate over the columns
    for col in tqdm(dataframe.columns):
        # Iterate over the rows in the current column with a sliding window
        for row in range(0, len(dataframe[col]) - (window_size + slide_size) + 1):
            window_range = row + window_size
            
            input_window = dataframe[col].iloc[row:window_range]
            input_window_list.append(input_window)
            
            label_window = dataframe[col].iloc[window_range:window_range + slide_size]
            label_window_list.append(label_window)
    return input_window_list, label_window_list

In [6]:
window_size = 3
slide_size = 1

test_input_list, test_label_list = create_window(df, window_size, slide_size)

100%|██████████| 147695/147695 [02:52<00:00, 853.91it/s] 


In [7]:
x_test = np.array(test_input_list)
y_test = np.array(test_label_list)

In [8]:
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1], 1)

In [13]:
model = tf.keras.models.load_model('models/model_1_2.keras')

In [14]:
y_pred = model.predict(x_test)

41540/41540 [==============================] - 177s 4ms/step


In [15]:
print(y_test.shape)
print(y_pred.shape)

(1329255, 1)
(1329255, 1)


In [16]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Root Mean Square Error:', rmse)

Root Mean Square Error: 1.4519097833822148


In [27]:
print("\nInput Window\n\n", x_test)
print("\nLabel Window\n\n", y_test)


Input Window

 [[[307.18]
  [306.48]
  [306.02]]

 [[306.48]
  [306.02]
  [309.36]]

 [[306.02]
  [309.36]
  [307.72]]

 ...

 [[305.64]
  [305.71]
  [305.78]]

 [[305.71]
  [305.78]
  [306.44]]

 [[305.78]
  [306.44]
  [304.84]]]

Label Window

 [[309.36]
 [307.72]
 [306.42]
 ...
 [306.44]
 [304.84]
 [306.64]]


In [23]:
print(y_test)

[[309.36]
 [307.72]
 [306.42]
 ...
 [306.44]
 [304.84]
 [306.64]]
